spring:
  main:
    web-application-type: reactive
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: bookQuery
          uri: lb://bookqueryservice
          predicates:
            - Path=/books/**
        - id: booksCommand
          uri: lb://BooksCommandService
          predicates:
            - Path=/book/**
        - id: borrowing
          uri: lb://BorrowingService
          predicates:
            - Path=/borrows/**
        - id: customer
          uri: lb://CustomerService
          predicates:
            - Path=/customers/**
        - id: review
          uri: lb://ReviewService
          predicates:
            - Path=/reviews/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://EurekaServer1:8761/eureka, http://EurekaServer2:8762/eureka
